//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJuiceMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EJuiceMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EJuice Maker.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all ingredients?
        ///
        ///All ingredients will be removed from all recipes!.
        /// </summary>
        internal static string AreYouSureDeleteAllIngredients {
            get {
                return ResourceManager.GetString("AreYouSureDeleteAllIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all ingredients from this recipe?.
        /// </summary>
        internal static string AreYouSureDeleteAllRecipeIngredients {
            get {
                return ResourceManager.GetString("AreYouSureDeleteAllRecipeIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all recipes?.
        /// </summary>
        internal static string AreYouSureDeleteAllRecipes {
            get {
                return ResourceManager.GetString("AreYouSureDeleteAllRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this ingredient?
        ///
        ///It will be removed from all recipes!.
        /// </summary>
        internal static string AreYouSureDeleteIngredient {
            get {
                return ResourceManager.GetString("AreYouSureDeleteIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this recipe?.
        /// </summary>
        internal static string AreYouSureDeleteRecipe {
            get {
                return ResourceManager.GetString("AreYouSureDeleteRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this ingredient from this recipe?.
        /// </summary>
        internal static string AreYouSureDeleteRecipeIngredient {
            get {
                return ResourceManager.GetString("AreYouSureDeleteRecipeIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bin_empty {
            get {
                object obj = ResourceManager.GetObject("bin_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calculator_edit {
            get {
                object obj = ResourceManager.GetObject("calculator_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Category_Basic {
            get {
                return ResourceManager.GetString("Category_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Category_Details {
            get {
                return ResourceManager.GetString("Category_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Category_Inventory {
            get {
                return ResourceManager.GetString("Category_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross_shield {
            get {
                object obj = ResourceManager.GetObject("cross_shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of Alcohol.
        /// </summary>
        internal static string Description_Ingredient_AlcoholContent {
            get {
                return ResourceManager.GetString("Description_Ingredient_AlcoholContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per mL in local currency.
        /// </summary>
        internal static string Description_Ingredient_CostPerMl {
            get {
                return ResourceManager.GetString("Description_Ingredient_CostPerMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp of the last restock of this ingredient.
        /// </summary>
        internal static string Description_Ingredient_LastPurchaseDate {
            get {
                return ResourceManager.GetString("Description_Ingredient_LastPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer name.
        /// </summary>
        internal static string Description_Ingredient_Manufacturer {
            get {
                return ResourceManager.GetString("Description_Ingredient_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the ingredient.
        /// </summary>
        internal static string Description_Ingredient_Name {
            get {
                return ResourceManager.GetString("Description_Ingredient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Nicotine (mg/mL).
        /// </summary>
        internal static string Description_Ingredient_NicotineDose {
            get {
                return ResourceManager.GetString("Description_Ingredient_NicotineDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient notes.
        /// </summary>
        internal static string Description_Ingredient_Notes {
            get {
                return ResourceManager.GetString("Description_Ingredient_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of Propylene Glycol.
        /// </summary>
        internal static string Description_Ingredient_PgContent {
            get {
                return ResourceManager.GetString("Description_Ingredient_PgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Alert threshold (mL).
        /// </summary>
        internal static string Description_Ingredient_QtyLowAlert {
            get {
                return ResourceManager.GetString("Description_Ingredient_QtyLowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled the Low Alert.
        /// </summary>
        internal static string Description_Ingredient_QtyLowAlertEnabled {
            get {
                return ResourceManager.GetString("Description_Ingredient_QtyLowAlertEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Warning threshold (mL).
        /// </summary>
        internal static string Description_Ingredient_QtyLowWarn {
            get {
                return ResourceManager.GetString("Description_Ingredient_QtyLowWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the Low Warning.
        /// </summary>
        internal static string Description_Ingredient_QtyLowWarnEnabled {
            get {
                return ResourceManager.GetString("Description_Ingredient_QtyLowWarnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of ingredient in inventory (mL).
        /// </summary>
        internal static string Description_Ingredient_QtyOnHand {
            get {
                return ResourceManager.GetString("Description_Ingredient_QtyOnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined stock-keeping unit
        ///
        ///This can be used as a Vendor SKU or a local inventory SKU..
        /// </summary>
        internal static string Description_Ingredient_SKU {
            get {
                return ResourceManager.GetString("Description_Ingredient_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Gravity in grams per mL.
        /// </summary>
        internal static string Description_Ingredient_SpecificGravity {
            get {
                return ResourceManager.GetString("Description_Ingredient_SpecificGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic type of the ingredient.
        /// </summary>
        internal static string Description_Ingredient_Type {
            get {
                return ResourceManager.GetString("Description_Ingredient_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Product Code.
        /// </summary>
        internal static string Description_Ingredient_UPC {
            get {
                return ResourceManager.GetString("Description_Ingredient_UPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor name.
        /// </summary>
        internal static string Description_Ingredient_Vendor {
            get {
                return ResourceManager.GetString("Description_Ingredient_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of Vegetable Glycerine.
        /// </summary>
        internal static string Description_Ingredient_VgContent {
            get {
                return ResourceManager.GetString("Description_Ingredient_VgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of Water.
        /// </summary>
        internal static string Description_Ingredient_WaterContent {
            get {
                return ResourceManager.GetString("Description_Ingredient_WaterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavoring.
        /// </summary>
        internal static string Description_IngredientType_Flavor {
            get {
                return ResourceManager.GetString("Description_IngredientType_Flavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicotine Base.
        /// </summary>
        internal static string Description_IngredientType_NicotineBase {
            get {
                return ResourceManager.GetString("Description_IngredientType_NicotineBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Description_IngredientType_None {
            get {
                return ResourceManager.GetString("Description_IngredientType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Description_IngredientType_Other {
            get {
                return ResourceManager.GetString("Description_IngredientType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propylene Glycol.
        /// </summary>
        internal static string Description_IngredientType_PropyleneGlycol {
            get {
                return ResourceManager.GetString("Description_IngredientType_PropyleneGlycol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetable Glycerin.
        /// </summary>
        internal static string Description_IngredientType_VegetableGlycerin {
            get {
                return ResourceManager.GetString("Description_IngredientType_VegetableGlycerin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diskette {
            get {
                object obj = ResourceManager.GetObject("diskette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol Content.
        /// </summary>
        internal static string DisplayName_Ingredient_AlcoholContent {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_AlcoholContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Per mL.
        /// </summary>
        internal static string DisplayName_Ingredient_CostPerMl {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_CostPerMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Purchase Date.
        /// </summary>
        internal static string DisplayName_Ingredient_LastPurchaseDate {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_LastPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string DisplayName_Ingredient_Manufacturer {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DisplayName_Ingredient_Name {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicotine Dose (mg/mL).
        /// </summary>
        internal static string DisplayName_Ingredient_NicotineDose {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_NicotineDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string DisplayName_Ingredient_Notes {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PG Content.
        /// </summary>
        internal static string DisplayName_Ingredient_PgContent {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_PgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Low Alert (mL).
        /// </summary>
        internal static string DisplayName_Ingredient_QtyLowAlert {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_QtyLowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Low Alert Enabled.
        /// </summary>
        internal static string DisplayName_Ingredient_QtyLowAlertEnabled {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_QtyLowAlertEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Low Warning (mL).
        /// </summary>
        internal static string DisplayName_Ingredient_QtyLowWarn {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_QtyLowWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Low Warning Enabled.
        /// </summary>
        internal static string DisplayName_Ingredient_QtyLowWarnEnabled {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_QtyLowWarnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity On Hand (mL).
        /// </summary>
        internal static string DisplayName_Ingredient_QtyOnHand {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_QtyOnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string DisplayName_Ingredient_SKU {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Gravity (g/mL).
        /// </summary>
        internal static string DisplayName_Ingredient_SpecificGravity {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_SpecificGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DisplayName_Ingredient_Type {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC.
        /// </summary>
        internal static string DisplayName_Ingredient_UPC {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_UPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string DisplayName_Ingredient_Vendor {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VG Content.
        /// </summary>
        internal static string DisplayName_Ingredient_VgContent {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_VgContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Content.
        /// </summary>
        internal static string DisplayName_Ingredient_WaterContent {
            get {
                return ResourceManager.GetString("DisplayName_Ingredient_WaterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load inventory: {0}.
        /// </summary>
        internal static string ErrorFailedToLoadInventory {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save inventory: {0}.
        /// </summary>
        internal static string ErrorFailedToSaveInventory {
            get {
                return ResourceManager.GetString("ErrorFailedToSaveInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid currency value..
        /// </summary>
        internal static string ErrorFormatCurrency {
            get {
                return ResourceManager.GetString("ErrorFormatCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid percentage..
        /// </summary>
        internal static string ErrorFormatPercent {
            get {
                return ResourceManager.GetString("ErrorFormatPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recipe has no ingredients..
        /// </summary>
        internal static string ErrorMixNoIngredients {
            get {
                return ResourceManager.GetString("ErrorMixNoIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough Propylene Glycol in recipe to mix..
        /// </summary>
        internal static string ErrorMixNotEnoughPg {
            get {
                return ResourceManager.GetString("ErrorMixNotEnoughPg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough Vegetable Glycerine in recipe to mix..
        /// </summary>
        internal static string ErrorMixNotEnoughVg {
            get {
                return ResourceManager.GetString("ErrorMixNotEnoughVg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe requires more Propylene Glycol than this mix ratio will allow..
        /// </summary>
        internal static string ErrorMixTooMuchPg {
            get {
                return ResourceManager.GetString("ErrorMixTooMuchPg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe requires more Vegetable Glycerine than this mix ratio will allow..
        /// </summary>
        internal static string ErrorMixTooMuchVg {
            get {
                return ResourceManager.GetString("ErrorMixTooMuchVg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_vertical_open {
            get {
                object obj = ResourceManager.GetObject("folder_vertical_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap house {
            get {
                object obj = ResourceManager.GetObject("house", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap house_go {
            get {
                object obj = ResourceManager.GetObject("house_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ingredients {
            get {
                object obj = ResourceManager.GetObject("ingredients", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mix {
            get {
                object obj = ResourceManager.GetObject("mix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can be mixed..
        /// </summary>
        internal static string MixValid {
            get {
                return ResourceManager.GetString("MixValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ingredient {0}.
        /// </summary>
        internal static string NewIngredientName {
            get {
                return ResourceManager.GetString("NewIngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe {0}.
        /// </summary>
        internal static string NewRecipeName {
            get {
                return ResourceManager.GetString("NewRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotAvailableAbbrv {
            get {
                return ResourceManager.GetString("NotAvailableAbbrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] recipes {
            get {
                object obj = ResourceManager.GetObject("recipes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string TabIngredients {
            get {
                return ResourceManager.GetString("TabIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_export {
            get {
                object obj = ResourceManager.GetObject("table_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_import {
            get {
                object obj = ResourceManager.GetObject("table_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_lightning {
            get {
                object obj = ResourceManager.GetObject("table_lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_save {
            get {
                object obj = ResourceManager.GetObject("table_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix.
        /// </summary>
        internal static string TabMix {
            get {
                return ResourceManager.GetString("TabMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string TabRecipes {
            get {
                return ResourceManager.GetString("TabRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick_shield {
            get {
                object obj = ResourceManager.GetObject("tick_shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg/mL.
        /// </summary>
        internal static string Unit_mgmL {
            get {
                return ResourceManager.GetString("Unit_mgmL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mL.
        /// </summary>
        internal static string Unit_mL {
            get {
                return ResourceManager.GetString("Unit_mL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes to {0}. Would you like to save them?.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
